// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

export const VV_COSMOS_DB_CONNECTION_STRING = 'VV_COSMOS_DB_CONNECTION_STRING';
export const VV_COSMOS_DB_ENDPOINT = 'VV_COSMOS_DB_ENDPOINT';
export const VV_COSMOS_DB_NAME = 'VV_COSMOS_DB_NAME';
export const VV_COMMUNICATION_SERVICES_CONNECTION_STRING = 'VV_COMMUNICATION_SERVICES_CONNECTION_STRING';
export const VV_MICROSOFT_BOOKINGS_URL_ENV_NAME = 'VV_MICROSOFT_BOOKINGS_URL';
export const VV_CHAT_ENABLED_ENV_NAME = 'VV_CHAT_ENABLED';
export const VV_SCREENSHARE_ENABLED_ENV_NAME = 'VV_SCREENSHARE_ENABLED';
export const VV_COMPANY_NAME_ENV_NAME = 'VV_COMPANY_NAME';
export const VV_COLOR_PALETTE_ENV_NAME = 'VV_COLOR_PALETTE';
export const VV_WAITING_TITLE_ENV_NAME = 'VV_WAITING_TITLE';
export const VV_WAITING_SUBTITLE_ENV_NAME = 'VV_WAITING_SUBTITLE';
export const VV_LOGO_URL_ENV_NAME = 'VV_LOGO_URL';
export const VV_POSTCALL_SURVEY_TYPE_ENV_NAME = 'VV_POSTCALL_SURVEY_TYPE';
export const VV_POSTCALL_SURVEY_OPTIONS_SURVEYURL_ENV_NAME = 'VV_POSTCALL_SURVEY_OPTIONS_SURVEYURL';
